// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace ApiClassLibrary.DataContext;

public partial class ApiIdentityDbContext : IdentityDbContext
{
     public ApiIdentityDbContext(DbContextOptions<ApiIdentityDbContext> options)
        : base(options)
    { }
}
