// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace ClassLibrary1.DataContext;

public partial class MyIdentityDbContext : IdentityDbContext
{
     public MyIdentityDbContext(DbContextOptions<MyIdentityDbContext> options)
        : base(options)
    { }
}
