// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using SharedProject1.Models;
using System;
using System.Collections.Generic;
#nullable disable

namespace ClassLibrary1.DataContext;

public partial class ReportDbContext : DbContext
{
    public virtual DbSet<RoadReport> RoadReports { get; set; }

    public ReportDbContext(DbContextOptions<ReportDbContext> options)
        : base(options)
    { }
}
